### ISSUE TITLE
Define the feature branches we are working on (Can we transfer this to milestones? I do not have permission)

### ISSUE THREAD

**Issue by Jeff-oakley** [CederGroupHub/smol#31]
As a followup of today's discussion. I have a few feature branches suggestions in mind that we probably want to work on in the near feature. Feel free to modify or comment on it. I feel some of them are a bit urgent as we may want to update in next Materials Project meeting or we want to send papers out.

The purpose of this issue is just to plan ahead of time so we can make progress with some directions, also we can prioritize something that is more important. We can also come back to amend and merge some branches later.

- [ ] Charge neutral feature branch (**mentioned by Fengyu already**)
- [ ] Lite version of smol for distribution to other group (**This is urgent in my opinion**)
- [ ] Cluster expansion automator branch (**Are we developing something independently or maybe just a new module?**)
- [ ] KMC related new features (**I suppose Tina and Zinab will work on it**)
- [ ] Sample selection features (**Peichen used to work on that, do we want to implement?**)
- [ ] New regularization/compressive sensing features
- [ ] SRO modules (**Bin can work on that**)
- [ ] Others that I forgot to mention
